# Generated by Django 5.2.6 on 2025-10-02 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audience', '0001_initial'),
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=255)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('content_text', models.TextField(blank=True, default='', help_text='Plain text body to send when no template is selected.')),
                ('template_id', models.UUIDField(blank=True, db_index=True, help_text='Nullable placeholder; later can be migrated to a proper FK.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('queuing', 'Queuing'), ('sending', 'Sending'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='When to start sending this email (UTC).', null=True)),
                ('audience', models.ForeignKey(blank=True, help_text='For first emails: whole audience. Can be null for future segments.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='audience.audience')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='campaigns.campaign')),
                ('depends_on', models.ForeignKey(blank=True, help_text='If set, this email is a follow-up to another email.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followups', to='emails.email')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['campaign', 'status'], name='emails_emai_campaig_079c1a_idx'), models.Index(fields=['campaign', 'scheduled_at'], name='emails_emai_campaig_401275_idx')],
            },
        ),
    ]
