# Generated by Django 5.2.6 on 2025-10-02 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='from_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
