# Generated by Django 5.2.6 on 2025-09-21 20:17

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audience', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone must be in international format (E.164), e.g., +201234567890.', regex='^\\+?[1-9]\\d{7,14}$')])),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced')], db_index=True, default='active', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('form', 'Form Signup'), ('csv', 'CSV Import')], db_index=True, default='manual', max_length=20)),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='audience.audience')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audience', 'status'], name='contacts_co_audienc_d585c6_idx'), models.Index(django.db.models.functions.text.Lower('email'), name='idx_contact_email_ci')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('audience'), name='uniq_contact_email_per_audience_ci'), models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='contact_email_not_empty')],
            },
        ),
    ]
