# Generated by Django 5.2.6 on 2025-09-21 22:17

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0001_initial'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='uniq_contact_email_per_audience_ci',
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='contact_email_not_empty',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='contacts_co_audienc_d585c6_idx',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_contact_email',
            old_name='idx_contact_email_ci',
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(django.db.models.functions.text.Lower('email'), condition=models.Q(('status', 'archived'), _negated=True), name='idx_contact_email_active_only'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('audience'), condition=models.Q(('status', 'archived'), _negated=True), name='email_per_audience_active'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'archived'), models.Q(('email', ''), _negated=True), _connector='OR'), name='contact_email_not_empty_if_active'),
        ),
    ]
