# Generated by Django 5.2.6 on 2025-09-21 22:23

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audience', '0001_initial'),
        ('contacts', '0002_remove_contact_uniq_contact_email_per_audience_ci_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contact',
            name='email_per_audience_active',
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='contact_email_not_empty_if_active',
        ),
        migrations.RemoveIndex(
            model_name='contact',
            name='idx_contact_email',
        ),
        migrations.RenameIndex(
            model_name='contact',
            new_name='idx_email_active',
            old_name='idx_contact_email_active_only',
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('audience'), condition=models.Q(('status', 'archived'), _negated=True), name='uniq_email_aud_active'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'archived'), models.Q(('email', ''), _negated=True), _connector='OR'), name='chk_email_not_empty_act'),
        ),
    ]
