# Generated by Django 5.2.6 on 2025-09-18 21:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['archived_at'], name='audience_au_archive_f72bf3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('user', 'name'), name='uq_active_audience_user_name'), models.UniqueConstraint(condition=models.Q(('archived_at__isnull', True)), fields=('user', 'slug'), name='uq_active_audience_user_slug')],
            },
        ),
    ]
