# Generated by Django 5.2.6 on 2025-09-29 17:28

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('schedule_type', models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled')], default='immediate', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='campaigns_c_status_96cb56_idx'), models.Index(fields=['schedule_type'], name='campaigns_c_schedul_8d2c68_idx'), models.Index(fields=['scheduled_at'], name='campaigns_c_schedul_e3e306_idx'), models.Index(fields=['user', 'status'], name='idx_campaign_user_status'), models.Index(condition=models.Q(('status', 'scheduled')), fields=['user', 'scheduled_at'], name='idx_camp_user_sched_active')],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), condition=models.Q(('status', 'archived'), _negated=True), name='uq_campaign_user_lower_name_active'), models.CheckConstraint(condition=models.Q(models.Q(('schedule_type', 'scheduled'), ('scheduled_at__isnull', False)), models.Q(('schedule_type', 'immediate'), ('scheduled_at__isnull', True)), _connector='OR'), name='ck_campaign_scheduled_at_matches_type')],
            },
        ),
    ]
