# Generated by Django 5.2.6 on 2025-10-02 16:30

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0004_tag_contact_tags_contact_contacts_co_tags_710a2a_gin_and_more'),
        ('emails', '0002_alter_email_from_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('opened', 'Opened'), ('clicked', 'Clicked')], db_index=True, default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, help_text='ID returned by ESP/SMTP provider for this recipient.', max_length=255, null=True)),
                ('last_event_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_recipients', to='contacts.contact')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='emails.email')),
            ],
        ),
        migrations.CreateModel(
            name='TrackEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('opened', 'Opened'), ('clicked', 'Clicked')], db_index=True, max_length=20)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tracking.emailrecipient')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['email', 'status'], name='tracking_em_email_i_d7e640_idx'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['contact', 'status'], name='tracking_em_contact_aea952_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailrecipient',
            unique_together={('email', 'contact')},
        ),
        migrations.AddIndex(
            model_name='trackevent',
            index=models.Index(fields=['recipient', 'event_type'], name='tracking_tr_recipie_45342a_idx'),
        ),
        migrations.AddIndex(
            model_name='trackevent',
            index=models.Index(fields=['event_type', 'occurred_at'], name='tracking_tr_event_t_23ce16_idx'),
        ),
    ]
