name: CI

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DEBUG=False" >> .env
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_PORT=5432" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}" >> .env
          echo "JWT_ALGORITHM=HS256" >> .env
          echo "CACHE_URL=redis://redis:6379/1" >> .env
          echo "CELERY_BROKER_URL=redis://redis:6379/0" >> .env
          echo "CELERY_RESULT_BACKEND=redis://redis:6379/2" >> .env


      - name: Build and start containers
        run: docker compose up -d --build

      - name: Run migrations
        run: docker compose exec -T web python manage.py migrate

      - name: Run tests
        run: docker compose exec -T web pytest -s -v
